project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: true
  resources:
    - codebooks/ #Add codebooks to docs
    - spotify/ #Add codebooks to docs

book:
  title: "Statistical Thinking"
  subtitle: "A Simulation Approach to Modeling Uncertainty"
  author: "Andrew Zieffler & Catalysts for Change"
  date: today
  sidebar:
    search: true
    background: '#383F56' #"#9f86c0"
  # cover-image: "figs/banner.png"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-modeling-and-simulation.qmd
    - 03-data-generation.qmd
    - 04-monte-carlo-simulation.qmd
    - 05-modeling-sampling-variation.qmd
    - 06-describing-distributions.qmd
    - 07-experimental-variation.qmd
    - 08-p-value.qmd
    - 09-internal-validity-evidence.qmd
    - 10-sampling-variation.qmd
    - 11-external-validity-evidence.qmd
    - 12-validity-evidence-and-inferences.qmd
    - 13-observational-studies.qmd
    - 14-statistical-estimation.qmd
    - 15-uncertainty-and-bias.qmd

# bibliography: ["assets/modeling.bib", "assets/packages.bib"]
# csl: 'assets/apa-single-spaced.csl'

format:
  html:
    theme:
      - cosmo
      - "assets/theme.scss"
    css: ["assets/sticky-notes.css"]
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    include-in-header: 'assets/statistical-thinking.js'
    code-copy: true
    highlight-style: 'a11y-dark'
    df-print: paged
    mainfont: 'Atkinson Hyperlegible'
    fontsize: '13pt'
    linestretch: '1.5em'
    linkcolor: '#c10088'
    toc: false
    toc-title: "On This Page"
editor: source
