# Generating Data from Models {-}

One core skill of a practicing statistician is to be able to generate random data from a model. Most of the models you will encounter in this course are referred to as *probability models*. That is just a fancy way of associating probabilities with different events, or outcomes, in a model. 

For example, the model of flipping a "fair" coin is a probability model. There are two events/outcomes in the model: heads and tails. Each of these outcomes has a probability of 0.5 associated with it. (Note that although we could say 50%, that probabilities are on the scale from 0 to 1, so are defined using decimal values.) 

In the in-class activity, *Generating Random Data&mdash;Cat Factory*, you will create several probability models to generate data about cats. To prepare for this activity, watch the [Probability Simulation](http://www.tinkerplots.com/movies/probability-simulation) TinkerPlots&trade; tutorial video.


<br />

<center>
<iframe width="560" height="420" src="https://www.youtube.com/embed/udeuvbJKGeI" frameborder="0" allowfullscreen></iframe>
</center>
